# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          version: "latest"
      - run: bun install
      - run: bun run build

  build-on-windows:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [lts/*]
        os: [windows-latest]
      fail-fast: false

    steps:
      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v3
        with:
          version: "latest"
      - run: npm install
      - run: npm run build
